#ifndef AUTOGENERATED_OPERATORS_H_
#define AUTOGENERATED_OPERATORS_H_
// This is autogenerated file.
// Do not edit it directly.

#include "intf.h"

template <class realT>
inCellDataT<realT> operator + (inCellDataT<realT> & first, inCellDataT<realT> & second)
{
	inCellDataT<realT> result;
	result.x = first.x + second.x;
	result.y = first.y + second.y;
	result.countryIdx = first.countryIdx + second.countryIdx;
	return result;
}

template <class realT, typename variableXxxType>
inCellDataT<realT> operator + (inCellDataT<realT> & first, variableXxxType & second)
{
	inCellDataT<realT> result;
	result.x = first.x + second;
	result.y = first.y + second;
	result.countryIdx = first.countryIdx + second;
	return result;
}

template <class realT>
inCellDataT<realT> operator - (inCellDataT<realT> & first, inCellDataT<realT> & second)
{
	inCellDataT<realT> result;
	result.x = first.x - second.x;
	result.y = first.y - second.y;
	result.countryIdx = first.countryIdx - second.countryIdx;
	return result;
}

template <class realT, typename variableXxxType>
inCellDataT<realT> operator - (inCellDataT<realT> & first, variableXxxType & second)
{
	inCellDataT<realT> result;
	result.x = first.x - second;
	result.y = first.y - second;
	result.countryIdx = first.countryIdx - second;
	return result;
}

template <class realT>
inCellDataT<realT> operator * (inCellDataT<realT> & first, inCellDataT<realT> & second)
{
	inCellDataT<realT> result;
	result.x = first.x * second.x;
	result.y = first.y * second.y;
	result.countryIdx = first.countryIdx * second.countryIdx;
	return result;
}

template <class realT, typename variableXxxType>
inCellDataT<realT> operator * (inCellDataT<realT> & first, variableXxxType & second)
{
	inCellDataT<realT> result;
	result.x = first.x * second;
	result.y = first.y * second;
	result.countryIdx = first.countryIdx * second;
	return result;
}

template <class realT>
inCellDataT<realT> operator / (inCellDataT<realT> & first, inCellDataT<realT> & second)
{
	inCellDataT<realT> result;
	result.x = first.x / second.x;
	result.y = first.y / second.y;
	result.countryIdx = first.countryIdx / second.countryIdx;
	return result;
}

template <class realT, typename variableXxxType>
inCellDataT<realT> operator / (inCellDataT<realT> & first, variableXxxType & second)
{
	inCellDataT<realT> result;
	result.x = first.x / second;
	result.y = first.y / second;
	result.countryIdx = first.countryIdx / second;
	return result;
}

template <class realT>
inCommonDataT<realT> operator + (inCommonDataT<realT> & first, inCommonDataT<realT> & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells + second.numCells;
	result.numCountries = first.numCountries + second.numCountries;
	result.beginYear = first.beginYear + second.beginYear;
	result.endYear = first.endYear + second.endYear;
	result.year = first.year + second.year;
	return result;
}

template <class realT, typename variableXxxType>
inCommonDataT<realT> operator + (inCommonDataT<realT> & first, variableXxxType & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells + second;
	result.numCountries = first.numCountries + second;
	result.beginYear = first.beginYear + second;
	result.endYear = first.endYear + second;
	result.year = first.year + second;
	return result;
}

template <class realT>
inCommonDataT<realT> operator - (inCommonDataT<realT> & first, inCommonDataT<realT> & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells - second.numCells;
	result.numCountries = first.numCountries - second.numCountries;
	result.beginYear = first.beginYear - second.beginYear;
	result.endYear = first.endYear - second.endYear;
	result.year = first.year - second.year;
	return result;
}

template <class realT, typename variableXxxType>
inCommonDataT<realT> operator - (inCommonDataT<realT> & first, variableXxxType & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells - second;
	result.numCountries = first.numCountries - second;
	result.beginYear = first.beginYear - second;
	result.endYear = first.endYear - second;
	result.year = first.year - second;
	return result;
}

template <class realT>
inCommonDataT<realT> operator * (inCommonDataT<realT> & first, inCommonDataT<realT> & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells * second.numCells;
	result.numCountries = first.numCountries * second.numCountries;
	result.beginYear = first.beginYear * second.beginYear;
	result.endYear = first.endYear * second.endYear;
	result.year = first.year * second.year;
	return result;
}

template <class realT, typename variableXxxType>
inCommonDataT<realT> operator * (inCommonDataT<realT> & first, variableXxxType & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells * second;
	result.numCountries = first.numCountries * second;
	result.beginYear = first.beginYear * second;
	result.endYear = first.endYear * second;
	result.year = first.year * second;
	return result;
}

template <class realT>
inCommonDataT<realT> operator / (inCommonDataT<realT> & first, inCommonDataT<realT> & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells / second.numCells;
	result.numCountries = first.numCountries / second.numCountries;
	result.beginYear = first.beginYear / second.beginYear;
	result.endYear = first.endYear / second.endYear;
	result.year = first.year / second.year;
	return result;
}

template <class realT, typename variableXxxType>
inCommonDataT<realT> operator / (inCommonDataT<realT> & first, variableXxxType & second)
{
	inCommonDataT<realT> result;
	result.numCells = first.numCells / second;
	result.numCountries = first.numCountries / second;
	result.beginYear = first.beginYear / second;
	result.endYear = first.endYear / second;
	result.year = first.year / second;
	return result;
}

template <class realT>
outCellDataT<realT> operator + (outCellDataT<realT> & first, outCellDataT<realT> & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea + second.forestArea;
	result.forestShare = first.forestShare + second.forestShare;
	return result;
}

template <class realT, typename variableXxxType>
outCellDataT<realT> operator + (outCellDataT<realT> & first, variableXxxType & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea + second;
	result.forestShare = first.forestShare + second;
	return result;
}

template <class realT>
outCellDataT<realT> operator - (outCellDataT<realT> & first, outCellDataT<realT> & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea - second.forestArea;
	result.forestShare = first.forestShare - second.forestShare;
	return result;
}

template <class realT, typename variableXxxType>
outCellDataT<realT> operator - (outCellDataT<realT> & first, variableXxxType & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea - second;
	result.forestShare = first.forestShare - second;
	return result;
}

template <class realT>
outCellDataT<realT> operator * (outCellDataT<realT> & first, outCellDataT<realT> & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea * second.forestArea;
	result.forestShare = first.forestShare * second.forestShare;
	return result;
}

template <class realT, typename variableXxxType>
outCellDataT<realT> operator * (outCellDataT<realT> & first, variableXxxType & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea * second;
	result.forestShare = first.forestShare * second;
	return result;
}

template <class realT>
outCellDataT<realT> operator / (outCellDataT<realT> & first, outCellDataT<realT> & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea / second.forestArea;
	result.forestShare = first.forestShare / second.forestShare;
	return result;
}

template <class realT, typename variableXxxType>
outCellDataT<realT> operator / (outCellDataT<realT> & first, variableXxxType & second)
{
	outCellDataT<realT> result;
	result.forestArea = first.forestArea / second;
	result.forestShare = first.forestShare / second;
	return result;
}

#endif
