#ifndef AUTOGENERATED_METADATA_H_
#define AUTOGENERATED_METADATA_H_
// This is autogenerated file.
// Do not edit it directly.

#include "struct_info.h"

#include "intf.h"



template <>
void struct_info_t< inCellDataT<double> >::define_metadata()
{
	add_variable(m_struct.STOPGAP);		// double
}

template <>
void struct_info_t< inCommonDataT<double> >::define_metadata()
{
	add_variable(m_struct.numCells);		// int
	add_variable(m_struct.beginYear);		// int
	add_variable(m_struct.endYear);		// int
	add_variable(m_struct.year);		// int
	add_variable(m_struct.STOPGAP);		// double
}

template <>
void struct_info_t< outCellDataT<double> >::define_metadata()
{
	add_variable(m_struct.STOPGAP);		// double
}

template <>
void struct_info_t< inCellDataT<float> >::define_metadata()
{
	add_variable(m_struct.STOPGAP);		// float
}

template <>
void struct_info_t< inCommonDataT<float> >::define_metadata()
{
	add_variable(m_struct.numCells);		// int
	add_variable(m_struct.beginYear);		// int
	add_variable(m_struct.endYear);		// int
	add_variable(m_struct.year);		// int
	add_variable(m_struct.STOPGAP);		// float
}

template <>
void struct_info_t< outCellDataT<float> >::define_metadata()
{
	add_variable(m_struct.STOPGAP);		// float
}

#endif
