#include "g4m.h"

// Autogenerated + struct utils
#include "autogenerated_metadata.h"
#include "structWriter.h"

template <class realT>
int computeModel();

int main(int argc, char * argv[])
{
	Timer stopwatch;
	stopwatch.start();

	computeModel<double>();

	stopwatch.stop();
	printf("Working time: %f\n", stopwatch.elapsedSeconds());

	return 0;
}

template <class realT>
int computeModel()
{
	dynamicArray(inCellDataT<realT>, inCellData);
	dynamicArray(outCellDataT<realT>, outCellData);
	inCommonDataT<realT> inCommonData;

	std::string guiFile = "data/gui_file.txt";

	inputFileInfoT info(guiFile);

	readInputs<realT>(info, inCellData, inCommonData, outCellData);

	// Initialize outputs
	simUnitsData simuData("data\\simu.bin");
	// Helper sets
	set<int> years;
	years.insert(2000);
	years.insert(2005);
	years.insert(2010);
	set<string> results;
	results.insert("forestArea");
	results.insert("forestShare");
	// Initialize dimensions of SIMU data class
	simuData.addDim("year", years);
	simuData.addDim("value", results);
	structWriter< outCellDataT<realT> > simuDataWriter(simuData);
	simuDataWriter.addOutputParam("forestArea");
	simuDataWriter.addOutputParam("forestShare");

	for (inCommonData.year = inCommonData.beginYear; inCommonData.year <= inCommonData.endYear; inCommonData.year++)
	{
		simuData.pointPush(inCommonData.year);
		parallelExecute< inCellDataT<realT>, inCommonDataT<realT>, outCellDataT<realT> > (
			&computeCell<realT>, inCellData, inCommonData, outCellData, inCommonData.numCells);
		// IMPLEMENT: writing to simu data
		// IMPLEMENT: passing address of simUnitsData to parallel execute to write in parallel
		simuData.pointPop();
	}

	printf("%f\n", outCellData[0].STOPGAP);

	dynamicFree(inCellData);
	dynamicFree(outCellData);

	return 0;
};