#ifndef AUTOGENERATED_METADATA_H_
#define AUTOGENERATED_METADATA_H_
// This is autogenerated file.
// Do not edit it directly.

#include "struct_info.h"

#include "intf.h"

//const int MAX_NUM_COUNTRIES = 300;


template <>
void struct_info_t< inCellDataT<double> >::define_metadata()
{
	add_variable(m_struct.x);		// double
	add_variable(m_struct.y);		// double
	add_variable(m_struct.simu);		// int
	add_variable(m_struct.countryIdx);		// int
	add_variable(m_struct.area);		// double
}

template <>
void struct_info_t< inCommonDataT<double> >::define_metadata()
{
	add_variable(m_struct.numCells);		// int
	add_variable(m_struct.numCountries);		// int
	add_variable(m_struct.beginYear);		// int
	add_variable(m_struct.endYear);		// int
	add_variable(m_struct.year);		// int
}

template <>
void struct_info_t< outCellDataT<double> >::define_metadata()
{
	add_variable(m_struct.forestArea);		// double
	add_variable(m_struct.forestShare);		// double
}

template <>
void struct_info_t< inCellDataT<float> >::define_metadata()
{
	add_variable(m_struct.x);		// float
	add_variable(m_struct.y);		// float
	add_variable(m_struct.simu);		// int
	add_variable(m_struct.countryIdx);		// int
	add_variable(m_struct.area);		// float
}

template <>
void struct_info_t< inCommonDataT<float> >::define_metadata()
{
	add_variable(m_struct.numCells);		// int
	add_variable(m_struct.numCountries);		// int
	add_variable(m_struct.beginYear);		// int
	add_variable(m_struct.endYear);		// int
	add_variable(m_struct.year);		// int
}

template <>
void struct_info_t< outCellDataT<float> >::define_metadata()
{
	add_variable(m_struct.forestArea);		// float
	add_variable(m_struct.forestShare);		// float
}

#endif
