#include "g4m.h"

// Autogenerated + struct utils
#include "autogenerated_metadata.h"
#include "structToMapWriter.h"

template <class realT>
int computeModel();

int main(int argc, char * argv[])
{
	Timer stopwatch;
	stopwatch.start();

	computeModel<float>();

	stopwatch.stop();
	printf("Working time: %f\n", stopwatch.elapsedSeconds());

	return 0;
}

template <class realT>
int computeModel()
{
	// Initialize outputs
	simUnitsData simuData("data\\simu.bin");
	// Helper sets
	vector<int> years;
	years.push_back(2000);
	years.push_back(2005);
	years.push_back(2010);
	vector<string> results;
	results.push_back("forestArea");
	results.push_back("forestShare");
	// Initialize dimensions of SIMU data class
	simuData.addDim("year", years);
	simuData.addDim("value", results);
	// SIMU data writer
	structToMapWriter< outCellDataT<realT> > simuDataWriter(simuData);
	simuDataWriter.addOutputParam("forestArea", DISTRIBUTE_PROPORTIONALLY);
	simuDataWriter.addOutputParam("forestShare", IS_CONSTANT);
	// Summary by countries
	tableData countrySummaryTable;
	vector<int> countries;
	countries.push_back(1);
	countries.push_back(2);
	countrySummaryTable.addDim("year", years);
	countrySummaryTable.addDim("country", countries);
	countrySummaryTable.addDim("value", results);
	structToTableWriter< outCellDataT<realT> > countrySummaryWriter(countrySummaryTable);

	// Initialize data
	dynamicArray(inCellDataT<realT>, inCellData);
	dynamicArray(outCellDataT<realT>, outCellData);
	dynamicArray(outCellDataT<realT>, outCountrySummaryData);
	inCommonDataT<realT> inCommonData;

	// Holder of data classes and structs
	dataContainersHolder<realT> pHolder(simuDataWriter, outCountrySummaryData);

	std::string guiFile = "data/gui_file.txt";

	inputFileInfoT info(guiFile);

	readInputs<realT>(info, simuData, inCellData, inCommonData, outCellData, outCountrySummaryData);

	for (inCommonData.year = inCommonData.beginYear; inCommonData.year <= inCommonData.endYear; inCommonData.year++)
	{
		simuData.pointPush(inCommonData.year);
		countrySummaryTable.pointPush(inCommonData.year);
		parallelExecute< inCellDataT<realT>, inCommonDataT<realT>, outCellDataT<realT> > (
			&computeCell<realT>, inCellData, inCommonData, outCellData, inCommonData.numCells, (void *)(& pHolder));
		simuData.pointPop();
		countrySummaryTable.pointPop();
	}

	dynamicFree(inCellData);
	dynamicFree(outCellData);
	dynamicFree(outCountrySummaryData);

	simuData.SaveToFile("..\\GLOBIOM GUI\\data\\maps", "my_test_map");

	return 0;
};