#ifndef AUTOGENERATED_OPERATORS_H_
#define AUTOGENERATED_OPERATORS_H_
// This is autogenerated file.
// Do not edit it directly.

#include "intf.h"

const int ARRAY_SIZE = 20;
const int NEW_CONST = ARRAY_SIZE+10;

struct_one operator + (struct_one & first, struct_one & second)
{
	struct_one result;
	result.intField = first.intField + second.intField;
	result.floatField = first.floatField + second.floatField;
	result.doubleField = first.doubleField + second.doubleField;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] + second.arrayField[g00];
	}
	return result;
}

template <typename variableXxxType>
struct_one operator + (struct_one & first, variableXxxType & second)
{
	struct_one result;
	result.intField = first.intField + second;
	result.floatField = first.floatField + second;
	result.doubleField = first.doubleField + second;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] + second;
	}
	return result;
}

struct_one operator - (struct_one & first, struct_one & second)
{
	struct_one result;
	result.intField = first.intField - second.intField;
	result.floatField = first.floatField - second.floatField;
	result.doubleField = first.doubleField - second.doubleField;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] - second.arrayField[g00];
	}
	return result;
}

template <typename variableXxxType>
struct_one operator - (struct_one & first, variableXxxType & second)
{
	struct_one result;
	result.intField = first.intField - second;
	result.floatField = first.floatField - second;
	result.doubleField = first.doubleField - second;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] - second;
	}
	return result;
}

struct_one operator * (struct_one & first, struct_one & second)
{
	struct_one result;
	result.intField = first.intField * second.intField;
	result.floatField = first.floatField * second.floatField;
	result.doubleField = first.doubleField * second.doubleField;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] * second.arrayField[g00];
	}
	return result;
}

template <typename variableXxxType>
struct_one operator * (struct_one & first, variableXxxType & second)
{
	struct_one result;
	result.intField = first.intField * second;
	result.floatField = first.floatField * second;
	result.doubleField = first.doubleField * second;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] * second;
	}
	return result;
}

struct_one operator / (struct_one & first, struct_one & second)
{
	struct_one result;
	result.intField = first.intField / second.intField;
	result.floatField = first.floatField / second.floatField;
	result.doubleField = first.doubleField / second.doubleField;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] / second.arrayField[g00];
	}
	return result;
}

template <typename variableXxxType>
struct_one operator / (struct_one & first, variableXxxType & second)
{
	struct_one result;
	result.intField = first.intField / second;
	result.floatField = first.floatField / second;
	result.doubleField = first.doubleField / second;
	for (int g00 = 0; g00 < ARRAY_SIZE; g00++)
	{
		result.arrayField[g00] = first.arrayField[g00] / second;
	}
	return result;
}

template <class realT>
template_struct<realT> operator + (template_struct<realT> & first, template_struct<realT> & second)
{
	template_struct<realT> result;
	result.realField = first.realField + second.realField;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] + second.realArray[g00];
	}
	return result;
}

template <class realT, typename variableXxxType>
template_struct<realT> operator + (template_struct<realT> & first, variableXxxType & second)
{
	template_struct<realT> result;
	result.realField = first.realField + second;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] + second;
	}
	return result;
}

template <class realT>
template_struct<realT> operator - (template_struct<realT> & first, template_struct<realT> & second)
{
	template_struct<realT> result;
	result.realField = first.realField - second.realField;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] - second.realArray[g00];
	}
	return result;
}

template <class realT, typename variableXxxType>
template_struct<realT> operator - (template_struct<realT> & first, variableXxxType & second)
{
	template_struct<realT> result;
	result.realField = first.realField - second;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] - second;
	}
	return result;
}

template <class realT>
template_struct<realT> operator * (template_struct<realT> & first, template_struct<realT> & second)
{
	template_struct<realT> result;
	result.realField = first.realField * second.realField;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] * second.realArray[g00];
	}
	return result;
}

template <class realT, typename variableXxxType>
template_struct<realT> operator * (template_struct<realT> & first, variableXxxType & second)
{
	template_struct<realT> result;
	result.realField = first.realField * second;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] * second;
	}
	return result;
}

template <class realT>
template_struct<realT> operator / (template_struct<realT> & first, template_struct<realT> & second)
{
	template_struct<realT> result;
	result.realField = first.realField / second.realField;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] / second.realArray[g00];
	}
	return result;
}

template <class realT, typename variableXxxType>
template_struct<realT> operator / (template_struct<realT> & first, variableXxxType & second)
{
	template_struct<realT> result;
	result.realField = first.realField / second;
	for (int g00 = 0; g00 < NEW_CONST; g00++)
	{
		result.realArray[g00] = first.realArray[g00] / second;
	}
	return result;
}

#endif
