//******************************************************************************
// country codes (new G4M (see ForWIKI), country order array and country ISO
//******************************************************************************
#ifndef countryCodes_new_cpp
#define countryCodes_new_cpp
void countryCodes()
{
for(int i=0;i<244;i++) {countryCodeOrder[i]=244;}
countryCodeOrder[	0	]=	12	;
countryCodeOrder[	1	]=	0	;
countryCodeOrder[	2	]=	6	;
countryCodeOrder[	3	]=	7	;
countryCodeOrder[	4	]=	1	;
countryCodeOrder[	5	]=	2	;
countryCodeOrder[	6	]=	5	;
countryCodeOrder[	7	]=	155	;
countryCodeOrder[	8	]=	228	;
countryCodeOrder[	9	]=	10	;
countryCodeOrder[	10	]=	11	;
countryCodeOrder[	11	]=	4	;
countryCodeOrder[	12	]=	8	;
countryCodeOrder[	13	]=	76	;
countryCodeOrder[	14	]=	9	;
countryCodeOrder[	15	]=	13	;
countryCodeOrder[	16	]=	14	;
countryCodeOrder[	17	]=	15	;
countryCodeOrder[	18	]=	35	;
countryCodeOrder[	19	]=	21	;
countryCodeOrder[	20	]=	23	;
countryCodeOrder[	21	]=	34	;
countryCodeOrder[	22	]=	18	;
countryCodeOrder[	23	]=	33	;
countryCodeOrder[	24	]=	17	;
countryCodeOrder[	25	]=	16	;
countryCodeOrder[	26	]=	27	;
countryCodeOrder[	27	]=	20	;
countryCodeOrder[	28	]=	22	;
countryCodeOrder[	29	]=	24	;
countryCodeOrder[	30	]=	26	;
countryCodeOrder[	31	]=	30	;
countryCodeOrder[	32	]=	19	;
countryCodeOrder[	33	]=	32	;
countryCodeOrder[	34	]=	25	;
countryCodeOrder[	35	]=	29	;
countryCodeOrder[	36	]=	28	;
countryCodeOrder[	37	]=	41	;
countryCodeOrder[	38	]=	38	;
countryCodeOrder[	39	]=	46	;
countryCodeOrder[	40	]=	210	;
countryCodeOrder[	41	]=	43	;
countryCodeOrder[	42	]=	44	;
countryCodeOrder[	43	]=	53	;
countryCodeOrder[	44	]=	37	;
countryCodeOrder[	45	]=	50	;
countryCodeOrder[	46	]=	49	;
countryCodeOrder[	47	]=	51	;
countryCodeOrder[	48	]=	47	;
countryCodeOrder[	49	]=	48	;
countryCodeOrder[	50	]=	39	;
countryCodeOrder[	51	]=	52	;
countryCodeOrder[	52	]=	55	;
countryCodeOrder[	53	]=	45	;
countryCodeOrder[	54	]=	40	;
countryCodeOrder[	55	]=	56	;
countryCodeOrder[	56	]=	57	;
countryCodeOrder[	57	]=	80	;
countryCodeOrder[	58	]=	59	;
countryCodeOrder[	59	]=	60	;
countryCodeOrder[	60	]=	58	;
countryCodeOrder[	61	]=	61	;
countryCodeOrder[	62	]=	3	;
countryCodeOrder[	63	]=	62	;
countryCodeOrder[	64	]=	63	;
countryCodeOrder[	65	]=	66	;
countryCodeOrder[	66	]=	240	;
countryCodeOrder[	67	]=	203	;
countryCodeOrder[	68	]=	67	;
countryCodeOrder[	69	]=	68	;
countryCodeOrder[	70	]=	72	;
countryCodeOrder[	71	]=	71	;
countryCodeOrder[	72	]=	70	;
countryCodeOrder[	73	]=	73	;
countryCodeOrder[	74	]=	69	;
countryCodeOrder[	75	]=	142	;
countryCodeOrder[	76	]=	77	;
countryCodeOrder[	77	]=	83	;
countryCodeOrder[	78	]=	79	;
countryCodeOrder[	79	]=	81	;
countryCodeOrder[	80	]=	82	;
countryCodeOrder[	81	]=	91	;
countryCodeOrder[	82	]=	87	;
countryCodeOrder[	83	]=	78	;
countryCodeOrder[	84	]=	92	;
countryCodeOrder[	85	]=	65	;
countryCodeOrder[	86	]=	84	;
countryCodeOrder[	87	]=	86	;
countryCodeOrder[	88	]=	85	;
countryCodeOrder[	89	]=	89	;
countryCodeOrder[	90	]=	74	;
countryCodeOrder[	91	]=	88	;
countryCodeOrder[	92	]=	93	;
countryCodeOrder[	93	]=	97	;
countryCodeOrder[	94	]=	95	;
countryCodeOrder[	95	]=	96	;
countryCodeOrder[	96	]=	54	;
countryCodeOrder[	97	]=	94	;
countryCodeOrder[	98	]=	98	;
countryCodeOrder[	99	]=	101	;
countryCodeOrder[	100	]=	100	;
countryCodeOrder[	101	]=	31	;
countryCodeOrder[	102	]=	104	;
countryCodeOrder[	103	]=	102	;
countryCodeOrder[	104	]=	103	;
countryCodeOrder[	105	]=	99	;
countryCodeOrder[	106	]=	106	;
countryCodeOrder[	107	]=	107	;
countryCodeOrder[	108	]=	108	;
countryCodeOrder[	109	]=	111	;
countryCodeOrder[	110	]=	109	;
countryCodeOrder[	111	]=	112	;
countryCodeOrder[	112	]=	113	;
countryCodeOrder[	113	]=	118	;
countryCodeOrder[	114	]=	36	;
countryCodeOrder[	115	]=	114	;
countryCodeOrder[	116	]=	184	;
countryCodeOrder[	117	]=	116	;
countryCodeOrder[	118	]=	117	;
countryCodeOrder[	119	]=	119	;
countryCodeOrder[	120	]=	121	;
countryCodeOrder[	121	]=	123	;
countryCodeOrder[	122	]=	124	;
countryCodeOrder[	123	]=	185	;
countryCodeOrder[	124	]=	125	;
countryCodeOrder[	125	]=	204	;
countryCodeOrder[	126	]=	122	;
countryCodeOrder[	127	]=	126	;
countryCodeOrder[	128	]=	127	;
countryCodeOrder[	129	]=	120	;
countryCodeOrder[	130	]=	128	;
countryCodeOrder[	131	]=	148	;
countryCodeOrder[	132	]=	144	;
countryCodeOrder[	133	]=	143	;
countryCodeOrder[	134	]=	130	;
countryCodeOrder[	135	]=	133	;
countryCodeOrder[	136	]=	141	;
countryCodeOrder[	137	]=	136	;
countryCodeOrder[	138	]=	129	;
countryCodeOrder[	139	]=	134	;
countryCodeOrder[	140	]=	135	;
countryCodeOrder[	141	]=	150	;
countryCodeOrder[	142	]=	146	;
countryCodeOrder[	143	]=	145	;
countryCodeOrder[	144	]=	163	;
countryCodeOrder[	145	]=	149	;
countryCodeOrder[	146	]=	138	;
countryCodeOrder[	147	]=	147	;
countryCodeOrder[	148	]=	137	;
countryCodeOrder[	149	]=	139	;
countryCodeOrder[	150	]=	131	;
countryCodeOrder[	151	]=	132	;
countryCodeOrder[	152	]=	140	;
countryCodeOrder[	153	]=	151	;
countryCodeOrder[	154	]=	156	;
countryCodeOrder[	155	]=	159	;
countryCodeOrder[	156	]=	162	;
countryCodeOrder[	157	]=	160	;
countryCodeOrder[	158	]=	158	;
countryCodeOrder[	159	]=	161	;
countryCodeOrder[	160	]=	154	;
countryCodeOrder[	161	]=	164	;
countryCodeOrder[	162	]=	153	;
countryCodeOrder[	163	]=	152	;
countryCodeOrder[	164	]=	157	;
countryCodeOrder[	165	]=	165	;
countryCodeOrder[	166	]=	166	;
countryCodeOrder[	167	]=	169	;
countryCodeOrder[	168	]=	174	;
countryCodeOrder[	169	]=	172	;
countryCodeOrder[	170	]=	173	;
countryCodeOrder[	171	]=	167	;
countryCodeOrder[	172	]=	170	;
countryCodeOrder[	173	]=	175	;
countryCodeOrder[	174	]=	177	;
countryCodeOrder[	175	]=	115	;
countryCodeOrder[	176	]=	176	;
countryCodeOrder[	177	]=	171	;
countryCodeOrder[	178	]=	168	;
countryCodeOrder[	179	]=	75	;
countryCodeOrder[	180	]=	178	;
countryCodeOrder[	181	]=	179	;
countryCodeOrder[	182	]=	180	;
countryCodeOrder[	183	]=	181	;
countryCodeOrder[	184	]=	182	;
countryCodeOrder[	185	]=	191	;
countryCodeOrder[	186	]=	205	;
countryCodeOrder[	187	]=	192	;
countryCodeOrder[	188	]=	196	;
countryCodeOrder[	189	]=	202	;
countryCodeOrder[	190	]=	183	;
countryCodeOrder[	191	]=	207	;
countryCodeOrder[	192	]=	199	;
countryCodeOrder[	193	]=	195	;
countryCodeOrder[	194	]=	64	;
countryCodeOrder[	195	]=	189	;
countryCodeOrder[	196	]=	200	;
countryCodeOrder[	197	]=	186	;
countryCodeOrder[	198	]=	193	;
countryCodeOrder[	199	]=	190	;
countryCodeOrder[	200	]=	206	;
countryCodeOrder[	201	]=	197	;
countryCodeOrder[	202	]=	198	;
countryCodeOrder[	203	]=	209	;
countryCodeOrder[	204	]=	208	;
countryCodeOrder[	205	]=	194	;
countryCodeOrder[	206	]=	211	;
countryCodeOrder[	207	]=	224	;
countryCodeOrder[	208	]=	42	;
countryCodeOrder[	209	]=	217	;
countryCodeOrder[	210	]=	215	;
countryCodeOrder[	211	]=	213	;
countryCodeOrder[	212	]=	218	;
countryCodeOrder[	213	]=	223	;
countryCodeOrder[	214	]=	216	;
countryCodeOrder[	215	]=	219	;
countryCodeOrder[	216	]=	220	;
countryCodeOrder[	217	]=	221	;
countryCodeOrder[	218	]=	222	;
countryCodeOrder[	219	]=	225	;
countryCodeOrder[	220	]=	212	;
countryCodeOrder[	221	]=	214	;
countryCodeOrder[	222	]=	226	;
countryCodeOrder[	223	]=	227	;
countryCodeOrder[	224	]=	230	;
countryCodeOrder[	225	]=	231	;
countryCodeOrder[	226	]=	229	;
countryCodeOrder[	227	]=	232	;
countryCodeOrder[	228	]=	234	;
countryCodeOrder[	229	]=	187	;
countryCodeOrder[	230	]=	235	;
countryCodeOrder[	231	]=	237	;
countryCodeOrder[	232	]=	238	;
countryCodeOrder[	233	]=	236	;
countryCodeOrder[	234	]=	233	;
countryCodeOrder[	235	]=	239	;
countryCodeOrder[	236	]=	188	;
countryCodeOrder[	237	]=	241	;
countryCodeOrder[	238	]=	201	;
countryCodeOrder[	239	]=	242	;
countryCodeOrder[	240	]=	243	;
countryCodeOrder[	241	]=	90	;
countryCodeOrder[	242	]=	105	;
countryCodeOrder[	243	]=	110	;


strcpy(counrtyOrderISO[0],"AFG");
strcpy(counrtyOrderISO[1],"ALA");
strcpy(counrtyOrderISO[2],"ALB");
strcpy(counrtyOrderISO[3],"DZA");
strcpy(counrtyOrderISO[4],"ASM");
strcpy(counrtyOrderISO[5],"AND");
strcpy(counrtyOrderISO[6],"AGO");
strcpy(counrtyOrderISO[7],"AIA");
strcpy(counrtyOrderISO[8],"ATA");
strcpy(counrtyOrderISO[9],"ATG");
strcpy(counrtyOrderISO[10],"ARG");
strcpy(counrtyOrderISO[11],"ARM");
strcpy(counrtyOrderISO[12],"ABW");
strcpy(counrtyOrderISO[13],"AUS");
strcpy(counrtyOrderISO[14],"AUT");
strcpy(counrtyOrderISO[15],"AZE");
strcpy(counrtyOrderISO[16],"BHS");
strcpy(counrtyOrderISO[17],"BHR");
strcpy(counrtyOrderISO[18],"BGD");
strcpy(counrtyOrderISO[19],"BRB");
strcpy(counrtyOrderISO[20],"BLR");
strcpy(counrtyOrderISO[21],"BEL");
strcpy(counrtyOrderISO[22],"BLZ");
strcpy(counrtyOrderISO[23],"BEN");
strcpy(counrtyOrderISO[24],"BMU");
strcpy(counrtyOrderISO[25],"BTN");
strcpy(counrtyOrderISO[26],"BOL");
strcpy(counrtyOrderISO[27],"BIH");
strcpy(counrtyOrderISO[28],"BWA");
strcpy(counrtyOrderISO[29],"BVT");
strcpy(counrtyOrderISO[30],"BRA");
strcpy(counrtyOrderISO[31],"IOT");
strcpy(counrtyOrderISO[32],"BRN");
strcpy(counrtyOrderISO[33],"BGR");
strcpy(counrtyOrderISO[34],"BFA");
strcpy(counrtyOrderISO[35],"BDI");
strcpy(counrtyOrderISO[36],"KHM");
strcpy(counrtyOrderISO[37],"CMR");
strcpy(counrtyOrderISO[38],"CAN");
strcpy(counrtyOrderISO[39],"CPV");
strcpy(counrtyOrderISO[40],"CYM");
strcpy(counrtyOrderISO[41],"CAF");
strcpy(counrtyOrderISO[42],"TCD");
strcpy(counrtyOrderISO[43],"CHL");
strcpy(counrtyOrderISO[44],"CHN");
strcpy(counrtyOrderISO[45],"CXR");
strcpy(counrtyOrderISO[46],"CCK");
strcpy(counrtyOrderISO[47],"COL");
strcpy(counrtyOrderISO[48],"COM");
strcpy(counrtyOrderISO[49],"COG");
strcpy(counrtyOrderISO[50],"COD");
strcpy(counrtyOrderISO[51],"COK");
strcpy(counrtyOrderISO[52],"CRI");
strcpy(counrtyOrderISO[53],"CIV");
strcpy(counrtyOrderISO[54],"HRV");
strcpy(counrtyOrderISO[55],"CUB");
strcpy(counrtyOrderISO[56],"CYP");
strcpy(counrtyOrderISO[57],"CZE");
strcpy(counrtyOrderISO[58],"DNK");
strcpy(counrtyOrderISO[59],"DJI");
strcpy(counrtyOrderISO[60],"DMA");
strcpy(counrtyOrderISO[61],"DOM");
strcpy(counrtyOrderISO[62],"ECU");
strcpy(counrtyOrderISO[63],"EGY");
strcpy(counrtyOrderISO[64],"SLV");
strcpy(counrtyOrderISO[65],"GNQ");
strcpy(counrtyOrderISO[66],"ERI");
strcpy(counrtyOrderISO[67],"EST");
strcpy(counrtyOrderISO[68],"ETH");
strcpy(counrtyOrderISO[69],"FRO");
strcpy(counrtyOrderISO[70],"FKL");
strcpy(counrtyOrderISO[71],"FJI");
strcpy(counrtyOrderISO[72],"FIN");
strcpy(counrtyOrderISO[73],"FRA");
strcpy(counrtyOrderISO[74],"GUF");
strcpy(counrtyOrderISO[75],"PYF");
strcpy(counrtyOrderISO[76],"ATF");
strcpy(counrtyOrderISO[77],"GAB");
strcpy(counrtyOrderISO[78],"GMB");
strcpy(counrtyOrderISO[79],"GEO");
strcpy(counrtyOrderISO[80],"DEU");
strcpy(counrtyOrderISO[81],"GHA");
strcpy(counrtyOrderISO[82],"GIB");
strcpy(counrtyOrderISO[83],"GBR");
strcpy(counrtyOrderISO[84],"GRC");
strcpy(counrtyOrderISO[85],"GRL");
strcpy(counrtyOrderISO[86],"GRD");
strcpy(counrtyOrderISO[87],"GLP");
strcpy(counrtyOrderISO[88],"GUM");
strcpy(counrtyOrderISO[89],"GTM");
strcpy(counrtyOrderISO[90],"GGY");
strcpy(counrtyOrderISO[91],"GIN");
strcpy(counrtyOrderISO[92],"GNB");
strcpy(counrtyOrderISO[93],"GUY");
strcpy(counrtyOrderISO[94],"HTI");
strcpy(counrtyOrderISO[95],"HMD");
strcpy(counrtyOrderISO[96],"HND");
strcpy(counrtyOrderISO[97],"HKG");
strcpy(counrtyOrderISO[98],"HUN");
strcpy(counrtyOrderISO[99],"ISL");
strcpy(counrtyOrderISO[100],"IND");
strcpy(counrtyOrderISO[101],"IDN");
strcpy(counrtyOrderISO[102],"IRN");
strcpy(counrtyOrderISO[103],"IRQ");
strcpy(counrtyOrderISO[104],"IRL");
strcpy(counrtyOrderISO[105],"IMN");
strcpy(counrtyOrderISO[106],"ISR");
strcpy(counrtyOrderISO[107],"ITA");
strcpy(counrtyOrderISO[108],"JAM");
strcpy(counrtyOrderISO[109],"JPN");
strcpy(counrtyOrderISO[110],"JEY");
strcpy(counrtyOrderISO[111],"JOR");
strcpy(counrtyOrderISO[112],"KAZ");
strcpy(counrtyOrderISO[113],"KEN");
strcpy(counrtyOrderISO[114],"KIR");
strcpy(counrtyOrderISO[115],"PRK");
strcpy(counrtyOrderISO[116],"KOR");
strcpy(counrtyOrderISO[117],"KWT");
strcpy(counrtyOrderISO[118],"KGZ");
strcpy(counrtyOrderISO[119],"LAO");
strcpy(counrtyOrderISO[120],"LVA");
strcpy(counrtyOrderISO[121],"LBN");
strcpy(counrtyOrderISO[122],"LSO");
strcpy(counrtyOrderISO[123],"LBR");
strcpy(counrtyOrderISO[124],"LBY");
strcpy(counrtyOrderISO[125],"LIE");
strcpy(counrtyOrderISO[126],"LTU");
strcpy(counrtyOrderISO[127],"LUX");
strcpy(counrtyOrderISO[128],"MAC");
strcpy(counrtyOrderISO[129],"MKD");
strcpy(counrtyOrderISO[130],"MDG");
strcpy(counrtyOrderISO[131],"MWI");
strcpy(counrtyOrderISO[132],"MYS");
strcpy(counrtyOrderISO[133],"MDV");
strcpy(counrtyOrderISO[134],"MLI");
strcpy(counrtyOrderISO[135],"MLT");
strcpy(counrtyOrderISO[136],"MHL");
strcpy(counrtyOrderISO[137],"MTQ");
strcpy(counrtyOrderISO[138],"MRT");
strcpy(counrtyOrderISO[139],"MUS");
strcpy(counrtyOrderISO[140],"MYT");
strcpy(counrtyOrderISO[141],"MEX");
strcpy(counrtyOrderISO[142],"FSM");
strcpy(counrtyOrderISO[143],"MDA");
strcpy(counrtyOrderISO[144],"MCO");
strcpy(counrtyOrderISO[145],"MNG");
strcpy(counrtyOrderISO[146],"MNE");
strcpy(counrtyOrderISO[147],"MSR");
strcpy(counrtyOrderISO[148],"MAR");
strcpy(counrtyOrderISO[149],"MOZ");
strcpy(counrtyOrderISO[150],"MMR");
strcpy(counrtyOrderISO[151],"NAM");
strcpy(counrtyOrderISO[152],"NRU");
strcpy(counrtyOrderISO[153],"NPL");
strcpy(counrtyOrderISO[154],"NLD");
strcpy(counrtyOrderISO[155],"ANT");
strcpy(counrtyOrderISO[156],"NCL");
strcpy(counrtyOrderISO[157],"NZL");
strcpy(counrtyOrderISO[158],"NIC");
strcpy(counrtyOrderISO[159],"NER");
strcpy(counrtyOrderISO[160],"NGA");
strcpy(counrtyOrderISO[161],"NIU");
strcpy(counrtyOrderISO[162],"NFK");
strcpy(counrtyOrderISO[163],"MNP");
strcpy(counrtyOrderISO[164],"NOR");
strcpy(counrtyOrderISO[165],"OMN");
strcpy(counrtyOrderISO[166],"PAK");
strcpy(counrtyOrderISO[167],"PLW");
strcpy(counrtyOrderISO[168],"PSE");
strcpy(counrtyOrderISO[169],"PAN");
strcpy(counrtyOrderISO[170],"PNG");
strcpy(counrtyOrderISO[171],"PRY");
strcpy(counrtyOrderISO[172],"PER");
strcpy(counrtyOrderISO[173],"PHL");
strcpy(counrtyOrderISO[174],"PCN");
strcpy(counrtyOrderISO[175],"POL");
strcpy(counrtyOrderISO[176],"PRT");
strcpy(counrtyOrderISO[177],"PRI");
strcpy(counrtyOrderISO[178],"QAT");
strcpy(counrtyOrderISO[179],"REU");
strcpy(counrtyOrderISO[180],"ROM");
strcpy(counrtyOrderISO[181],"RUS");
strcpy(counrtyOrderISO[182],"RWA");
strcpy(counrtyOrderISO[183],"SHN");
strcpy(counrtyOrderISO[184],"KNA");
strcpy(counrtyOrderISO[185],"LCA");
strcpy(counrtyOrderISO[186],"SPM");
strcpy(counrtyOrderISO[187],"VCT");
strcpy(counrtyOrderISO[188],"WSM");
strcpy(counrtyOrderISO[189],"SMR");
strcpy(counrtyOrderISO[190],"STP");
strcpy(counrtyOrderISO[191],"SAU");
strcpy(counrtyOrderISO[192],"SEN");
strcpy(counrtyOrderISO[193],"SRB");
strcpy(counrtyOrderISO[194],"SYC");
strcpy(counrtyOrderISO[195],"SLE");
strcpy(counrtyOrderISO[196],"SGP");
strcpy(counrtyOrderISO[197],"SVK");
strcpy(counrtyOrderISO[198],"SVN");
strcpy(counrtyOrderISO[199],"SLB");
strcpy(counrtyOrderISO[200],"SOM");
strcpy(counrtyOrderISO[201],"ZAF");
strcpy(counrtyOrderISO[202],"SGS");
strcpy(counrtyOrderISO[203],"ESP");
strcpy(counrtyOrderISO[204],"LKA");
strcpy(counrtyOrderISO[205],"SDN");
strcpy(counrtyOrderISO[206],"SUR");
strcpy(counrtyOrderISO[207],"SJM");
strcpy(counrtyOrderISO[208],"SWZ");
strcpy(counrtyOrderISO[209],"SWE");
strcpy(counrtyOrderISO[210],"CHE");
strcpy(counrtyOrderISO[211],"SYR");
strcpy(counrtyOrderISO[212],"TWN");
strcpy(counrtyOrderISO[213],"TJK");
strcpy(counrtyOrderISO[214],"TZA");
strcpy(counrtyOrderISO[215],"THA");
strcpy(counrtyOrderISO[216],"TLS");
strcpy(counrtyOrderISO[217],"TGO");
strcpy(counrtyOrderISO[218],"TKL");
strcpy(counrtyOrderISO[219],"TON");
strcpy(counrtyOrderISO[220],"TTG");
strcpy(counrtyOrderISO[221],"TUN");
strcpy(counrtyOrderISO[222],"TUR");
strcpy(counrtyOrderISO[223],"TKM");
strcpy(counrtyOrderISO[224],"TCA");
strcpy(counrtyOrderISO[225],"TUV");
strcpy(counrtyOrderISO[226],"UGA");
strcpy(counrtyOrderISO[227],"UKR");
strcpy(counrtyOrderISO[228],"ARE");
strcpy(counrtyOrderISO[229],"USA");
strcpy(counrtyOrderISO[230],"UMI");
strcpy(counrtyOrderISO[231],"URY");
strcpy(counrtyOrderISO[232],"UZB");
strcpy(counrtyOrderISO[233],"VUT");
strcpy(counrtyOrderISO[234],"VAT");
strcpy(counrtyOrderISO[235],"VEN");
strcpy(counrtyOrderISO[236],"VNM");
strcpy(counrtyOrderISO[237],"VGB");
strcpy(counrtyOrderISO[238],"VIR");
strcpy(counrtyOrderISO[239],"WLF");
strcpy(counrtyOrderISO[240],"ESH");
strcpy(counrtyOrderISO[241],"YEM");
strcpy(counrtyOrderISO[242],"ZMB");
strcpy(counrtyOrderISO[243],"ZWE");
strcpy(counrtyOrderISO[244],"???");

countryOrderName[0]="Afghanistan";
countryOrderName[1]="Åland Islands";
countryOrderName[2]="Albania";
countryOrderName[3]="Algeria";
countryOrderName[4]="American Samoa";
countryOrderName[5]="Andorra";
countryOrderName[6]="Angola";
countryOrderName[7]="Anguilla";
countryOrderName[8]="Antarctica";
countryOrderName[9]="Antigua and Barbuda";
countryOrderName[10]="Argentina";
countryOrderName[11]="Armenia";
countryOrderName[12]="Aruba";
countryOrderName[13]="Australia";
countryOrderName[14]="Austria";
countryOrderName[15]="Azerbaijan";
countryOrderName[16]="Bahamas";
countryOrderName[17]="Bahrain";
countryOrderName[18]="Bangladesh";
countryOrderName[19]="Barbados";
countryOrderName[20]="Belarus";
countryOrderName[21]="Belgium";
countryOrderName[22]="Belize";
countryOrderName[23]="Benin";
countryOrderName[24]="Bermuda";
countryOrderName[25]="Bhutan";
countryOrderName[26]="Bolivia";
countryOrderName[27]="Bosnia and Herzegovina";
countryOrderName[28]="Botswana";
countryOrderName[29]="Bouvet Island";
countryOrderName[30]="Brazil";
countryOrderName[31]="British Indian Territory";
countryOrderName[32]="Brunei Darussalam";
countryOrderName[33]="Bulgaria";
countryOrderName[34]="Burkina Faso";
countryOrderName[35]="Burundi";
countryOrderName[36]="Cambodia";
countryOrderName[37]="Cameroon";
countryOrderName[38]="Canada";
countryOrderName[39]="Cape Verde";
countryOrderName[40]="Cayman Islands";
countryOrderName[41]="Central African Republic";
countryOrderName[42]="Chad";
countryOrderName[43]="Chile";
countryOrderName[44]="China";
countryOrderName[45]="Christmas Island";
countryOrderName[46]="Cocos Islands";
countryOrderName[47]="Colombia";
countryOrderName[48]="Comoros";
countryOrderName[49]="Congo";
countryOrderName[50]="Democratic Republic of the Congo";
countryOrderName[51]="Cook Islands";
countryOrderName[52]="Costa Rica";
countryOrderName[53]="Côte d\\\'Ivoire";
countryOrderName[54]="Croatia";
countryOrderName[55]="Cuba";
countryOrderName[56]="Cyprus";
countryOrderName[57]="Czech Republic";
countryOrderName[58]="Denmark";
countryOrderName[59]="Djibouti";
countryOrderName[60]="Dominica";
countryOrderName[61]="Dominican Republic";
countryOrderName[62]="Ecuador";
countryOrderName[63]="Egypt";
countryOrderName[64]="El Salvador";
countryOrderName[65]="Equatorial Guinea";
countryOrderName[66]="Eritrea";
countryOrderName[67]="Estonia";
countryOrderName[68]="Ethiopia";
countryOrderName[69]="Faeroe Islands";
countryOrderName[70]="Falkland Islands";
countryOrderName[71]="Fiji";
countryOrderName[72]="Finland";
countryOrderName[73]="France";
countryOrderName[74]="French Guiana";
countryOrderName[75]="French Polynesia";
countryOrderName[76]="French Southern Territories";
countryOrderName[77]="Gabon";
countryOrderName[78]="Gambia";
countryOrderName[79]="Georgia";
countryOrderName[80]="Germany";
countryOrderName[81]="Ghana";
countryOrderName[82]="Gibraltar";
countryOrderName[83]="United Kingdom";
countryOrderName[84]="Greece";
countryOrderName[85]="Greenland";
countryOrderName[86]="Grenada";
countryOrderName[87]="Guadeloupe";
countryOrderName[88]="Guam";
countryOrderName[89]="Guatemala";
countryOrderName[90]="Guernsey";
countryOrderName[91]="Guinea";
countryOrderName[92]="Guinea-Bissau";
countryOrderName[93]="Guyana";
countryOrderName[94]="Haiti";
countryOrderName[95]="Heard Island and McDonald Islands";
countryOrderName[96]="Honduras";
countryOrderName[97]="Hong Kong";
countryOrderName[98]="Hungary";
countryOrderName[99]="Iceland";
countryOrderName[100]="India";
countryOrderName[101]="Indonesia";
countryOrderName[102]="Iran (Islamic Republic of)";
countryOrderName[103]="Iraq";
countryOrderName[104]="Ireland";
countryOrderName[105]="Isle of Man";
countryOrderName[106]="Israel";
countryOrderName[107]="Italy";
countryOrderName[108]="Jamaica";
countryOrderName[109]="Japan";
countryOrderName[110]="Jersey";
countryOrderName[111]="Jordan";
countryOrderName[112]="Kazakhstan";
countryOrderName[113]="Kenya";
countryOrderName[114]="Kiribati";
countryOrderName[115]="Democratic People\\\'s Republic of Korea";
countryOrderName[116]="Republic of Korea";
countryOrderName[117]="Kuwait";
countryOrderName[118]="Kyrgyzstan";
countryOrderName[119]="Lao People\\\'s Democratic Republic";
countryOrderName[120]="Latvia";
countryOrderName[121]="Lebanon";
countryOrderName[122]="Lesotho";
countryOrderName[123]="Liberia";
countryOrderName[124]="Libyan Arab Jamahiriya";
countryOrderName[125]="Liechtenstein";
countryOrderName[126]="Lithuania";
countryOrderName[127]="Luxembourg";
countryOrderName[128]="Macao";
countryOrderName[129]="The former Yugoslav Republic of Macedonia";
countryOrderName[130]="Madagascar";
countryOrderName[131]="Malawi";
countryOrderName[132]="Malaysia";
countryOrderName[133]="Maldives";
countryOrderName[134]="Mali";
countryOrderName[135]="Malta";
countryOrderName[136]="Marshall Islands";
countryOrderName[137]="Martinique";
countryOrderName[138]="Mauritania";
countryOrderName[139]="Mauritius";
countryOrderName[140]="Mayotte";
countryOrderName[141]="Mexico";
countryOrderName[142]="Micronesia (Federated States of)";
countryOrderName[143]="Republic of Moldova";
countryOrderName[144]="Monaco";
countryOrderName[145]="Mongolia";
countryOrderName[146]="Montenegro";
countryOrderName[147]="Montserrat";
countryOrderName[148]="Morocco";
countryOrderName[149]="Mozambique";
countryOrderName[150]="Myanmar";
countryOrderName[151]="Namibia";
countryOrderName[152]="Nauru";
countryOrderName[153]="Nepal";
countryOrderName[154]="Netherlands";
countryOrderName[155]="Netherlands Antilles";
countryOrderName[156]="New Caledonia";
countryOrderName[157]="New Zealand";
countryOrderName[158]="Nicaragua";
countryOrderName[159]="Niger";
countryOrderName[160]="Nigeria";
countryOrderName[161]="Niue";
countryOrderName[162]="Norfolk Islands";
countryOrderName[163]="Northern Mariana Islands";
countryOrderName[164]="Norway";
countryOrderName[165]="Oman";
countryOrderName[166]="Pakistan";
countryOrderName[167]="Palau";
countryOrderName[168]="Palestinian Territories";
countryOrderName[169]="Panama";
countryOrderName[170]="Papua New Guinea";
countryOrderName[171]="Paraguay";
countryOrderName[172]="Peru";
countryOrderName[173]="Philippines";
countryOrderName[174]="Pitcairn";
countryOrderName[175]="Poland";
countryOrderName[176]="Portugal";
countryOrderName[177]="Puerto Rico";
countryOrderName[178]="Qatar";
countryOrderName[179]="Reunion";
countryOrderName[180]="Romania";
countryOrderName[181]="Russian Federation";
countryOrderName[182]="Rwanda";
countryOrderName[183]="Saint Helena";
countryOrderName[184]="Saint Kitts and Nevis";
countryOrderName[185]="Saint Lucia";
countryOrderName[186]="Saint Pierre and Miquelon";
countryOrderName[187]="Saint Vincent and the Grenadines";
countryOrderName[188]="Samoa";
countryOrderName[189]="San Marino";
countryOrderName[190]="Sao Tome and Principe";
countryOrderName[191]="Saudi Arabia";
countryOrderName[192]="Senegal";
countryOrderName[193]="Republic of Serbia";
countryOrderName[194]="Seychelles";
countryOrderName[195]="Sierra Leone";
countryOrderName[196]="Singapore";
countryOrderName[197]="Slovakia";
countryOrderName[198]="Slovenia";
countryOrderName[199]="Solomon Islands";
countryOrderName[200]="Somalia";
countryOrderName[201]="South Africa";
countryOrderName[202]="South Georgia and The South Sandwich Islands";
countryOrderName[203]="Spain";
countryOrderName[204]="Sri Lanka";
countryOrderName[205]="Sudan";
countryOrderName[206]="Suriname";
countryOrderName[207]="Svalbard and Jan Mayen";
countryOrderName[208]="Swaziland";
countryOrderName[209]="Sweden";
countryOrderName[210]="Switzerland";
countryOrderName[211]="Syrian Arab Republic";
countryOrderName[212]="Taiwan";
countryOrderName[213]="Tajikistan";
countryOrderName[214]="United Republic of Tanzania";
countryOrderName[215]="Thailand";
countryOrderName[216]="Timor-Leste";
countryOrderName[217]="Togo";
countryOrderName[218]="Tokelau";
countryOrderName[219]="Tonga";
countryOrderName[220]="Trinidad and Tobago";
countryOrderName[221]="Tunisia";
countryOrderName[222]="Turkey";
countryOrderName[223]="Turkmenistan";
countryOrderName[224]="Turks and Caicos Islands";
countryOrderName[225]="Tuvalu";
countryOrderName[226]="Uganda";
countryOrderName[227]="Ukraine";
countryOrderName[228]="United Arab Emirates";
countryOrderName[229]="United States of America";
countryOrderName[230]="United States Minor Outlying Islands";
countryOrderName[231]="Uruguay";
countryOrderName[232]="Uzbekistan";
countryOrderName[233]="Vanuatu";
countryOrderName[234]="Vatican City";
countryOrderName[235]="Venezuela";
countryOrderName[236]="Viet Nam";
countryOrderName[237]="Virgin Islands, British";
countryOrderName[238]="Virgin Islands, U.S.";
countryOrderName[239]="Wallis and Futuna";
countryOrderName[240]="Western Sahara";
countryOrderName[241]="Yemen";
countryOrderName[242]="Zambia";
countryOrderName[243]="Zimbabwe";
countryOrderName[244]="noName";
//----------------------------------------------------
countryRegName[0]="noName";
countryRegName[1]="Austria";
countryRegName[2]="Belgium";
countryRegName[3]="Bulgaria";
countryRegName[4]="Cyprus";
countryRegName[5]="Czech Republic";
countryRegName[6]="Denmark";
countryRegName[7]="Estonia";
countryRegName[8]="Finland";
countryRegName[9]="France";
countryRegName[10]="Germany";
countryRegName[11]="Greece";
countryRegName[12]="Hungary";
countryRegName[13]="Ireland";
countryRegName[14]="Italy";
countryRegName[15]="Latvia";
countryRegName[16]="Lithuania";
countryRegName[17]="Luxembourg";
countryRegName[18]="Malta";
countryRegName[19]="Netherlands";
countryRegName[20]="Poland";
countryRegName[21]="Portugal";
countryRegName[22]="Romania";
countryRegName[23]="Slovakia";
countryRegName[24]="Slovenia";
countryRegName[25]="Spain";
countryRegName[26]="Sweden";
countryRegName[27]="United Kingdom";
countryRegName[28]="ANZ";
countryRegName[29]="BrazilReg";
countryRegName[30]="CanadaReg";
countryRegName[31]="ChinaReg";
countryRegName[32]="Former_USSR";
countryRegName[33]="IndiaReg";
countryRegName[34]="JapanReg";
countryRegName[35]="MexicoReg";
countryRegName[36]="MidEastNorthAfr";
countryRegName[37]="Pacific_Islands";
countryRegName[38]="RCAM (Rest of Central America)";
countryRegName[39]="RCEU (Rest of Central Europe)";
countryRegName[40]="ROWE (Rest of Western Europe)";
countryRegName[41]="RSAM (Rest of South America)";
countryRegName[42]="RSAS (Rest of South Asia)";
countryRegName[43]="RSEA_OPA (Rest of South-East Asia Pacific)";
countryRegName[44]="RSEA_PAC (Rest of South-East Asia Pacific)";
countryRegName[45]="SouthAfrReg";
countryRegName[46]="SouthKorea";
countryRegName[47]="SubSaharanAfr (Sub-Saharan Africa)";
countryRegName[48]="TurkeyReg";
countryRegName[49]="USAReg";

 
}
#endif
