#ifndef AUTOGENERATED_METADATA_H_
#define AUTOGENERATED_METADATA_H_
// This is autogenerated file.
// Do not edit it directly.

#include "struct_info.h"

#include "intf.h"

//const int ARRAY_SIZE = 20;
//const int NEW_CONST = ARRAY_SIZE+10;

//int intArray[ARRAY_SIZE];

template <>
void struct_info_t< struct_one >::define_metadata()
{
	add_variable(m_struct.intField);		// int
	add_variable(m_struct.floatField);		// float
	add_variable(m_struct.doubleField);		// double
	add_variable(m_struct.arrayField);		// double
}

template <>
void struct_info_t< template_struct<double> >::define_metadata()
{
	add_variable(m_struct.realField);		// double
	add_variable(m_struct.realArray);		// double
}

template <>
void struct_info_t< template_struct<float> >::define_metadata()
{
	add_variable(m_struct.realField);		// float
	add_variable(m_struct.realArray);		// float
}

#endif
